apiVersion: v1
kind: PersistentVolume
metadata:
  name: sd15-cache-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/rancher/rke2/sd15-cache
    type: DirectoryOrCreate
