apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd15-cache
  namespace: sd15-api
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
