apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-models-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/rancher/rke2/llm-models
    type: DirectoryOrCreate
