apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models
  namespace: llm
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
